export const GATEWAY_VERSION = 10;
export const GATEWAY_URL = "wss://gateway.discord.gg";

export const GatewayOpcodes = {
  DISPATCH: 0,
  HEARTBEAT: 1,
  IDENTIFY: 2,
  PRESENCE_UPDATE: 3,
  VOICE_STATE_UPDATE: 4,
  RESUME: 6,
  RECONNECT: 7,
  REQUEST_GUILD_MEMBERS: 8,
  INVALID_SESSION: 9,
  HELLO: 10,
  HEARTBEAT_ACK: 11,
  REQUEST_SOUNDBOARD_SOUNDS: 31,
} as const;

export const GatewayCloseCodes = {
  UNKNOWN_ERROR: 4000,
  UNKNOWN_OPCODE: 4001,
  DECODE_ERROR: 4002,
  NOT_AUTHENTICATED: 4003,
  AUTHENTICATION_FAILED: 4004,
  ALREADY_AUTHENTICATED: 4005,
  INVALID_SEQ: 4007,
  RATE_LIMITED: 4008,
  SESSION_TIMED_OUT: 4009,
  INVALID_SHARD: 4010,
  SHARDING_REQUIRED: 4011,
  INVALID_API_VERSION: 4012,
  INVALID_INTENTS: 4013,
  DISALLOWED_INTENTS: 4014,
} as const;

export const GatewayCloseCodeMessages: Record<number, string> = {
  4004: "Authentication failed - Invalid token",
  4010: "Invalid shard configuration",
  4011: "Sharding required - Bot is in too many guilds",
  4012: "Invalid API version",
  4013: "Invalid intent(s)",
  4014: "Disallowed intent(s) - You need to enable privileged intents in the Discord Developer Portal",
};

/**
 * Gateway Intents are bitwise values used to filter which Gateway events your application receives.
 *
 * @see {@link https://discord.com/developers/docs/events/gateway#gateway-intents}
 */
export const GatewayIntents = {
  /** GUILD_CREATE, GUILD_UPDATE, GUILD_DELETE, GUILD_ROLE_CREATE, GUILD_ROLE_UPDATE, GUILD_ROLE_DELETE, CHANNEL_CREATE, CHANNEL_UPDATE, CHANNEL_DELETE, CHANNEL_PINS_UPDATE, THREAD_CREATE, THREAD_UPDATE, THREAD_DELETE, THREAD_LIST_SYNC, THREAD_MEMBER_UPDATE, THREAD_MEMBERS_UPDATE, STAGE_INSTANCE_CREATE, STAGE_INSTANCE_UPDATE, STAGE_INSTANCE_DELETE */
  GUILDS: 1 << 0,
  /** GUILD_MEMBER_ADD, GUILD_MEMBER_UPDATE, GUILD_MEMBER_REMOVE, THREAD_MEMBERS_UPDATE (Privileged Intent) */
  GUILD_MEMBERS: 1 << 1,
  /** GUILD_AUDIT_LOG_ENTRY_CREATE, GUILD_BAN_ADD, GUILD_BAN_REMOVE */
  GUILD_MODERATION: 1 << 2,
  /** GUILD_EMOJIS_UPDATE, GUILD_STICKERS_UPDATE, GUILD_SOUNDBOARD_SOUND_CREATE, GUILD_SOUNDBOARD_SOUND_UPDATE, GUILD_SOUNDBOARD_SOUND_DELETE, GUILD_SOUNDBOARD_SOUNDS_UPDATE */
  GUILD_EXPRESSIONS: 1 << 3,
  /** GUILD_INTEGRATIONS_UPDATE, INTEGRATION_CREATE, INTEGRATION_UPDATE, INTEGRATION_DELETE */
  GUILD_INTEGRATIONS: 1 << 4,
  /** WEBHOOKS_UPDATE */
  GUILD_WEBHOOKS: 1 << 5,
  /** INVITE_CREATE, INVITE_DELETE */
  GUILD_INVITES: 1 << 6,
  /** VOICE_CHANNEL_EFFECT_SEND, VOICE_STATE_UPDATE */
  GUILD_VOICE_STATES: 1 << 7,
  /** PRESENCE_UPDATE (Privileged Intent) */
  GUILD_PRESENCES: 1 << 8,
  /** MESSAGE_CREATE, MESSAGE_UPDATE, MESSAGE_DELETE, MESSAGE_DELETE_BULK */
  GUILD_MESSAGES: 1 << 9,
  /** MESSAGE_REACTION_ADD, MESSAGE_REACTION_REMOVE, MESSAGE_REACTION_REMOVE_ALL, MESSAGE_REACTION_REMOVE_EMOJI */
  GUILD_MESSAGE_REACTIONS: 1 << 10,
  /** TYPING_START */
  GUILD_MESSAGE_TYPING: 1 << 11,
  /** MESSAGE_CREATE, MESSAGE_UPDATE, MESSAGE_DELETE, CHANNEL_PINS_UPDATE */
  DIRECT_MESSAGES: 1 << 12,
  /** MESSAGE_REACTION_ADD, MESSAGE_REACTION_REMOVE, MESSAGE_REACTION_REMOVE_ALL, MESSAGE_REACTION_REMOVE_EMOJI */
  DIRECT_MESSAGE_REACTIONS: 1 << 13,
  /** TYPING_START */
  DIRECT_MESSAGE_TYPING: 1 << 14,
  /** Allows receiving message content fields (content, embeds, attachments, components, poll) (Privileged Intent) */
  MESSAGE_CONTENT: 1 << 15,
  /** GUILD_SCHEDULED_EVENT_CREATE, GUILD_SCHEDULED_EVENT_UPDATE, GUILD_SCHEDULED_EVENT_DELETE, GUILD_SCHEDULED_EVENT_USER_ADD, GUILD_SCHEDULED_EVENT_USER_REMOVE */
  GUILD_SCHEDULED_EVENTS: 1 << 16,
  /** AUTO_MODERATION_RULE_CREATE, AUTO_MODERATION_RULE_UPDATE, AUTO_MODERATION_RULE_DELETE */
  AUTO_MODERATION_CONFIGURATION: 1 << 20,
  /** AUTO_MODERATION_ACTION_EXECUTION */
  AUTO_MODERATION_EXECUTION: 1 << 21,
  /** MESSAGE_POLL_VOTE_ADD, MESSAGE_POLL_VOTE_REMOVE */
  GUILD_MESSAGE_POLLS: 1 << 24,
  /** MESSAGE_POLL_VOTE_ADD, MESSAGE_POLL_VOTE_REMOVE */
  DIRECT_MESSAGE_POLLS: 1 << 25,
} as const;
